services:
  postgres:
    image: postgres:17-alpine
    container_name: micronotes-postgres
    environment:
      - POSTGRES_USER=micronotes
      - POSTGRES_PASSWORD=micronotes123
      - POSTGRES_DB=micronotes
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    networks:
      - micronotes-network




networks:
  micronotes-network:
    driver: bridge

volumes:
  postgres_data: